name: Unbelievable Exception
description: "Error occurred successfully!"

encoding: utf-8

highlighter: rouge

paginate: 15
paginate_path: :num

exclude:
  - test
  - .sass-cache

post_categories:
  projects:
    name: Projects
  devoops:
    name: DevOops

url: http://www.unbelievableexception.com
github: https://github.com/ataxexe/ataxexe.github.io

owner:
  name: Marcelo Guimarães
  nickname: Ataxexe
  contacts:
    GitHub: http://github.com/ataxexe
    YouTube: http://youtube.com/ataxexe
    LinkedIn: http://linkedin.com/in/ataxexe
    Twitter: http://twitter.com/ataxexe
