name: Unbelievable Exception
description: "Error occurred successfully!"

encoding: utf-8

highlighter: rouge

paginate: 15
paginate_path: :num

permalink: pretty

defaults:
  -
    values:
      highlight: androidstudio

exclude:
  - test
  - .sass-cache

url: http://www.unbelievableexception.com
github: https://github.com/ataxexe/ataxexe.github.io
