name: Unbelievable Exception
description: "Error occurred successfully!"

encoding: utf-8

highlighter: rouge

paginate: 15
paginate_path: :num

permalink: /posts/:categories/:year/:month/:day/:title.html

defaults:
  -
    values:
      highlight: androidstudio
      language: en_US

exclude:
  - test
  - .sass-cache

url: http://www.unbelievableexception.com
github: https://github.com/ataxexe/ataxexe.github.io

plugins:
  - jekyll-paginate
  - i18n
  - closure-compiler
  - sass
